config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  #root   'movies#index'
  get   '/movies',   to: 'movies#index'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :movies do
    collection do
      get 'search'
    end
    
    resources :reviews do
      member do
        put "like", to: "reviews#upvote"
        put "dislike", to: "reviews#downvote"
      end
    end
    
    
    
    
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :reviews,          only: [:create, :destroy] 
  resources :relationships,       only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @reviews  = current_user.reviews.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end
  
  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">

    <aside class="col-md-4">
      <div class="new-review-form">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      </div>
    </aside>
    <div class="col-md-8">
      <h3>Reviews Feed</h3>
      <%= render 'shared/feed' %>
    </div>

  </div>
  <%else%>
    <div class="center jumbotron">
      
    <div class="welcome">
    <div class="image"><%=image_tag("video.png", alt: "Video logo", class: "logo")
              %> </div>
       <h1>Welcome to the MovieShare</h1>
    </div>
  

    <h2>
      Sign up below to share your movie reviews of your favourtie films with like minded people!
    </h2>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>

              
  <%end%>