config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  #root   'movies#index'
  get   '/movies',   to: 'movies#index'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :movies do
    collection do
      get 'search'
    end
    
    resources :reviews do
      member do
        put "like", to: "reviews#upvote"
        put "dislike", to: "reviews#downvote"
      end
    end
    
    
    
    
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :reviews,          only: [:create, :destroy] 
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
    <footer class="footer">
      <small>
        The <a href="https://bitbucket.org/oreillyalan88/movie-review-app">Ruby on Rails MovieShare App</a>
        by <a href="https://ie.linkedin.com/in/witalanoreilly">Alan O' Reilly</a>
      </small>
    </footer

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
          <%= link_to image_tag("logo.png", alt: "Site logo"),
              root_path, class: 'navbar-brand'%>
        <%= link_to "MovieShare", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <% if logged_in? %>
              <li><%= link_to "Users", users_path %></li>
              <li><%= link_to "Movies", movies_url %></li>
             <%= form_tag search_movies_path, method: :get, class: "navbar-form navbar-right" , role: "search" do %>
             <p>
               <%= text_field_tag :search, params[:search],placeholder: "Search for a movie", class: "form-control" %>
               <%= submit_tag "Search", name: nil, class: "btn btn-default1" %>
             </p>
             <% end %>
             <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Genres <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <% Genre.all.each do |genre| %>
                  <li class= "<%= 'active' if params[:genre] == genre.name%>">
                    <%= link_to genre.name, movies_path(genre: genre.name), class: "link" %>
                    </li>
                  <% end %>
                </ul>
               </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li><%= link_to "Add Movie", new_movie_path %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/application.html.erb
    <!DOCTYPE html>
    <html>
      <head>
        <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all',
                                                  'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      </head>
      <body>
        <%= render 'layouts/header' %> 
        <div class="container">
          <% flash.each do |message_type, message| %>   
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
          <%= yield %>
          <%= render 'layouts/footer' %>

        </div>
      </body>
    </html>